sudo: required
language: generic 
services: 
  - docker

before_install:
  - docker build -t ajpeng/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ajpeng/docker-react npm run test