sudo: required
language: generic 
services: 
  - docker

before_install:
  - docker build -t ajpeng/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ajpeng/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react"
  env: "React-env"
  bucket_name: "elasticbeanstalk-us-east-2-426719348382"
  bucket_path: "react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY